from __future__ import annotations

import argparse

from ai_job_hunter.application import load_json, write_application_packet


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate an application/proposal packet from a selected job candidate and user profile."
    )
    parser.add_argument(
        "--candidate-json",
        required=True,
        help="Path to selected_candidate.json generated by ai-job-hunter",
    )
    parser.add_argument(
        "--profile",
        required=True,
        help="Path to user profile JSON. See docs/USER_REQUIRED_INFO.md",
    )
    parser.add_argument(
        "--output-dir",
        default="output/application_packet",
        help="Directory to write application packet files",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    candidate_payload = load_json(args.candidate_json)
    profile = load_json(args.profile)
    result = write_application_packet(candidate_payload, profile, args.output_dir)

    if not result["ok"]:
        print(f"Missing required user info: {result['missing_count']}")
        print(f"Missing info report written to: {result['missing_path']}")
        return 2

    print("Application packet generated.")
    print(f"Draft: {result['draft_path']}")
    print(f"Checklist: {result['checklist_path']}")
    print(f"Payload: {result['payload_path']}")
    print(f"Dry-run log: {result['log_path']}")
    print("No live application or post was submitted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
